[features]
seeds = false
skip-lint = false
[programs.localnet]
interacting_program = "2q1iXZ2fHMMimgppsFfghRMdBGk3iT9qxDo84Ltk1fwt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sougata/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
cluster = "http://localhost:8899"
