[features]
seeds = false
skip-lint = false

[programs.localnet]
getter_setter = "434s3aws1dnq4bq4UBzYiVU3qUWKr7B92zXFMtkbXZBS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sougata/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
cluster = "http://localhost:8899"
